### ISSUE TITLE
Loop Groups variable

### ISSUE THREAD

**Issue by OCEISCO** [DeabLabs/cannoli#37]
I've been searching for this feature for quite some time - the ability to control processing one line at a time of a long list or one table row. I was happy to find it in the Cannoli College, but unfortunately, when using the {{#}} variable, 

- {{#}}, {{##}} returns the number "1" in every loop, regardless the actual loop (also in the The loop number variable example).
- The loging card display the loop number title currectly.

I'm wondering if this might be due to my local LLM setup or perhaps there's a conflict with another plugin. Could you please offer some guidance on this?

Additionally, as an idea, is it possible to retrieve a line number and temporarily store it in a card? This could potentially be a useful feature for organizing and manipulating data.

**Comment by blindmansion** [comment]
Thanks for raising this! Probably broke this a few updates ago. I think it should be a fairly quick fix, fingers crossed.

**Comment by blindmansion** [comment]
@OCEISCO This has been fixed! Update cannoli and give it a try.

Wrt your suggestion, can you expand a bit? What do you mean by store the line number in a card?

**Comment by OCEISCO** [comment]
Thank you, @blindmansion,  this update worked like a charm and exactly met my needs.

As someone with little to no experience in coding, I've been relying on the Cannoli Collage and trying to approach this workflow. I hope there will be comprehensive documentation available soon, as I have a lot of use for this tool.

Regarding storing single-row data in a node: I wanted to create a node that carries only one table row per loop iteration, allowing me to apply specific functions to it without additional context. It would be great if there was a simple way to retrieve rows of data one by one.

I've been testing this function for more challenging analysis jobs and created a short test using various local Ollama models (dolphin-llama3, llama3:instruct, etc.) to process a mockup table row-by-row. While I was able to overcome some challenges, there were others that I still can't figure out how to solve.

Since I wasn't able to save individual notes or aggregate results to a note, I tried using the logging node as a temporary repository for loop outputs. However, reducing the final logging node is challenging due to its inclusion of user, assistant, and config data.

---
To generate a "clean" transfer of data (single row), I used multiple steps to slim down the logging content node. This involved creating a variable grey arrow and then further cleaning it using another variable.

During these tests, I applied nodes that checked results accuracy and created workflows to report the results. I also used another node to summarize the results logging node with mixed success.

---
What I'm struggling with is how to save a new note every loop iteration. I've tried using the {{#}} variable to append the note name, but it didn't work. Since I couldn't find a way to append text to an existing note, I'm not sure what to do. 
Please advise.

I am sharing my test canvas, I am sure there is an easier way to do it.

[Loop Table Analysis template.zip](https://github.com/DeabLabs/cannoli/files/15440740/Loop.Table.Analysis.template.zip)

**Comment by blindmansion** [comment]
It's always so fun to see complex cannolis like this, thank you!

The key to doing this is using the formatter node (cannoli college 3.3) to append the new stuff onto the result we've built up so far.

There's actually several ways to do this, one by writing to a note, one by writing to a floating node, and the one I'll attach here. However, when I tried the one where we write the data to a floating node (see cannoli college 3.1 on how we write to floating nodes), I discovered some bugs with the way floating nodes currently work. So thank you for raising this! We wouldn't have caught these very annoying bugs otherwise.

The canvas file i've attached should be enough to explain the principle behind this solution, which should be extensible to other similar things (that is if I understood your question correctly in the first place)

[Building a result in a loop.canvas.zip](https://github.com/DeabLabs/cannoli/files/15441839/Building.a.result.in.a.loop.canvas.zip)

Let me know if this works!
